server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/user
    username: root
    password: 1qaz!QAZ
mybatis:
  mapper-locations: classpath*:mapper/*.xml
  type-aliases-package: com.example.springbootapitest.pojo
logging:
  level:
    root: debug
    org:
      springframework: debug
      org:
        mybatis: debug
